# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Item

# Model Form Field configuration
form: $/iis/inventory/models/item/fields.yaml

# Model Class name
modelClass: IIS\Inventory\Models\Item

# Default redirect location
defaultRedirect: iis/inventory/items

# Create page
create:
    title: Create Item
    redirect: iis/inventory/items/update/:id
    redirectClose: iis/inventory/items

# Update page
update:
    title: Edit Item
    redirect: iis/inventory/items
    redirectClose: iis/inventory/items

# Preview page
preview:
    title: Preview Item