# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: $/iis/inventory/models/item/columns.yaml

# Model Class name
modelClass: IIS\Inventory\Models\Item

# List Title
title: Manage Items

# Link URL for each record
recordUrl: iis/inventory/items/update/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 20

# Displays the list column set up button
showSetup: true

# Displays the sorting link on each column
showSorting: true

# Default sorting column
defaultSort:
   column: created_at
   direction: desc

# Display checkboxes next to each record
showCheckboxes: true

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt

filter: config_filter.yaml